databases:
  - name: abnormal-db
    plan: starter

services:
  - type: web
    name: abnormal-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt
    # Remove startCommand here
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: abnormal-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
    plan: starter
    autoDeploy: true

  - type: web
    name: abnormal-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    # Remove startCommand here
    envVars:
      - key: REACT_APP_API_URL
        value: "https://abnormal-backend.onrender.com/api"
    plan: starter
    autoDeploy: true
